apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-systools
  labels:
    app: docker-systools
    tier: infra
spec:
  selector:
    matchLabels:
      app: docker-systools
      tier: infra
  replicas: 1
  template:
    metadata:
      labels:
        app: docker-systools
        tier: infra
    spec:
#      hostNetwork: true
#      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: docker-systools
        image: ponte124/docker-systools:stable-aarch64
        imagePullPolicy: Always
        command:
          - sh
          - -c
          - |
            sleep infinity        
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext:
          privileged: true
          capabilities:
            add:
              - NET_ADMIN
              - NET_BIND_SERVICE
              - NET_RAW
              - SYS_ADMIN
